# Generated by Django 5.1.1 on 2024-10-06 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='gread',
            field=models.CharField(default='A', max_length=1),
        ),
    ]
